apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
      - name: app
        image: nginx:1.17.6
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: deployment-secret
